name: "Docker Stack Deploy"
description: "Deploy a Docker Stack"
author: "Shane"
branding:
  icon: "layers"
  color: "green"

inputs:
  host:
    description: "Docker Host"
    required: true
  port:
    description: "Docker Port"
    default: "22"
    required: false
  user:
    description: "Docker User"
    required: true
  pass:
    description: "Docker Pass"
    required: false
  ssh_key:
    description: "SSH Key File"
    required: false
  file:
    description: "Docker Compose File"
    default: "docker-compose.yaml"
    required: false
  name:
    description: "Docker Stack Name"
    required: true
  env_file:
    description: "Environment File"
    required: false
  env:
    description: "Environment Variables"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "INPUT_HOST=${{ inputs.HOST }}" >> $GITHUB_ENV
        echo "INPUT_PORT=${{ inputs.PORT }}" >> $GITHUB_ENV
        echo "INPUT_USER=${{ inputs.USER }}" >> $GITHUB_ENV
        echo "INPUT_PASS=${{ inputs.PASS }}" >> $GITHUB_ENV
        echo "INPUT_FILE=${{ inputs.FILE }}" >> $GITHUB_ENV
        echo "INPUT_NAME=${{ inputs.NAME }}" >> $GITHUB_ENV
        echo "INPUT_ENV_FILE=${{ inputs.ENV_FILE }}" >> $GITHUB_ENV
        echo "INPUT_ENV=${{ inputs.ENV }}" >> $GITHUB_ENV

    - name: Create SSH file
      shell: bash
      run: |
        mkdir -p /root/.ssh
        echo "${{ inputs.SSH_KEY }}" > /root/.ssh/id_rsa
        chmod 0600 /root/.ssh/id_rsa

    - name: Add SSH key to agent
      shell: bash
      run: |
        eval $(ssh-agent -s)
        ssh-add /root/.ssh/id_rsa

    - name: Run script
      shell: bash
      run: deno run -A ${{ github.action_path }}/src/index.js

